version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      frontend:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /apps/admin
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      admin:
        patterns: ['*']
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
