'use client';
import {useEffect,useState} from 'react';
import {api,mediaUrl} from '../lib/api-client';
import {resources,emptyRecord,titleOf} from '../lib/resources';
import MediaPicker from './media-picker';
import RichEditor from './rich-editor';

export default function ContentManager({resource}){
 const config=resources[resource], [items,setItems]=useState([]),[record,setRecord]=useState(null),[initial,setInitial]=useState(''),[language,setLanguage]=useState('en'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[picker,setPicker]=useState(false),[categories,setCategories]=useState({});
 const dirty=record&&JSON.stringify(record)!==initial;
 async function load(){setLoading(true);try{setItems(await api('/admin/'+resource));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();for(const field of config.fields.filter(f=>f.type==='category'))api('/admin/'+field.source).then(data=>setCategories(old=>({...old,[field.source]:data}))).catch(e=>setError(e.message));if(new URLSearchParams(window.location.search).has('new'))begin(emptyRecord(config));},[resource]);
 useEffect(()=>{const handler=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 function begin(item){const next=structuredClone(item);setRecord(next);setInitial(JSON.stringify(next));setLanguage('en');setError('');setNotice('');}
 function back(){if(dirty&&!window.confirm('Discard your unsaved changes?'))return;setRecord(null);setError('');}
 const set=(key,value)=>setRecord(old=>({...old,[key]:value}));
 const translated=(key,value)=>setRecord(old=>({...old,translations:{...old.translations,[language]:{...old.translations[language],[key]:value}}}));
 async function save(e){
  e.preventDefault();setError('');setNotice('');
  for(const lang of ['en','tr'])for(const field of config.translations){const text=record.translations[lang]?.[field.key]||'';const visible=field.type==='rich'?new DOMParser().parseFromString(text,'text/html').body.textContent:text;if(field.required&&visible.trim().length<2){setLanguage(lang);setError('Complete '+field.label+' in '+(lang==='en'?'English':'Turkish')+' (at least 2 characters).');return;}}
  for(const field of config.fields)if(field.required&&(record[field.key]===null||record[field.key]===undefined||String(record[field.key]).trim()==='')){setError('Complete '+field.label+'.');return;}
  const payload={...record};
  for(const field of config.fields){if(field.type==='number'||field.type==='category')payload[field.key]=record[field.key]==null||record[field.key]===''?null:Number(record[field.key]);if(field.type==='datetime-local')payload[field.key]=record[field.key]?new Date(record[field.key]).toISOString():null;}
  if(config.gallery)payload.images=record.images.map(({media_id,alt_text,is_cover})=>({media_id,alt_text:alt_text||'',is_cover}));
  setBusy(true);try{const result=await api('/admin/'+resource+(record.id?'/'+record.id:''),{method:record.id?'PUT':'POST',body:payload});setRecord(result);setInitial(JSON.stringify(result));setNotice('Your '+config.singular+' has been saved.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}
 }
 async function remove(item){
  if(!window.confirm((config.statuses?'Remove this '+config.singular+' from the website and workspace?':'Deactivate this category? Existing content will be preserved.')))return;
  setBusy(true);setError('');try{await api('/admin/'+resource+'/'+item.id,{method:'DELETE'});setNotice(config.statuses?'Content removed.':'Category deactivated.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}
 }
 function selected(media){
  if(config.gallery){if(!record.images.some(i=>i.media_id===media.id))set('images',[...record.images,{media_id:media.id,url:media.public_url,alt_text:media.alt_text||'',is_cover:record.images.length===0}]);}
  else setRecord(old=>({...old,[config.imageKey]:media.id,image:media.public_url}));
  setPicker(false);
 }
 function reorder(index,direction){const next=[...record.images];[next[index],next[index+direction]]=[next[index+direction],next[index]];set('images',next);}
 function fieldInput(field,value,onChange){
  const props={id:field.key,name:field.key,value:value??'',onChange:e=>onChange(e.target.value),maxLength:field.maxLength,min:field.min,max:field.max,required:field.required};
  if(field.type==='checkbox')return <label className="checkbox-field" key={field.key}><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{field.label}</label>;
  if(field.type==='rich')return <div className="field" key={field.key}><span>{field.label} *</span><RichEditor key={(record.id||'new')+language} value={value} onChange={onChange}/></div>;
  return <label className="field" key={field.key} htmlFor={field.key}>{field.label}{field.required?' *':''}{field.type==='textarea'?<textarea {...props} rows={4}/>:field.type==='category'?<select {...props}><option value="">Select a category</option>{(categories[field.source]||[]).map(c=><option key={c.id} value={c.id} disabled={!c.is_active}>{c.translations.en.name}{!c.is_active?' (inactive)':''}</option>)}</select>:<input {...props} type={field.type} value={field.type==='datetime-local'&&value?localDate(value):props.value}/>} {field.help&&<small className="field-help">{field.help}</small>}</label>;
 }
 const visible=items.filter(item=>(titleOf(item)+' '+(item.slug||'')).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||item.status===filter));
 return <main className="content">
  <div className="page-heading"><div><p className="eyebrow">STUDIO CONTENT</p><h1>{record?(record.id?'Edit '+config.singular:'New '+config.singular):config.title}</h1><p>{config.intro}</p></div>{record?<button className="secondary" onClick={back}>← Back to {config.title.toLowerCase()}</button>:<button className="primary" onClick={()=>begin(emptyRecord(config))}>+ Add {config.singular}</button>}</div>
  {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice success" role="status">{notice}</p>}
  {record?<form onSubmit={save} noValidate><fieldset disabled={busy} className="editor-fieldset"><div className="editor-layout"><section className="panel"><div className="panel-heading"><h2>Story & details</h2><span className="subtle">EN + TR</span></div><div className="language-tabs" role="tablist" aria-label="Content language">{['en','tr'].map(lang=><button type="button" role="tab" aria-selected={language===lang} aria-controls="translation-panel" key={lang} onClick={()=>setLanguage(lang)}>{lang==='en'?'English':'Türkçe'} <span>{config.translations.filter(f=>!f.required||(record.translations[lang]?.[f.key]||'').trim()).length}/{config.translations.length}</span></button>)}</div><div id="translation-panel" role="tabpanel" aria-label={language==='en'?'English content':'Turkish content'}>{config.translations.map(field=>fieldInput(field,record.translations[language]?.[field.key]||'',value=>translated(field.key,value)))}</div></section><aside className="editor-aside"><section className="panel"><h2>Settings</h2>{config.fields.map(field=>fieldInput(field,record[field.key],value=>set(field.key,value)))}{config.statuses&&<label className="field">Publication status<select value={record.status} onChange={e=>set('status',e.target.value)}>{config.statuses.map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label>}<p className="field-help">Complete both language versions before saving. Published content is visible on the website.</p></section>{config.imageKey&&<section className="panel"><h2>{config.imageLabel}</h2>{record[config.imageKey]&&record.image?<><img className="cover-preview" src={mediaUrl(record.image)} alt="Selected photograph"/><button type="button" className="text-button" onClick={()=>setRecord(old=>({...old,[config.imageKey]:null,image:null}))}>Remove image</button></>:<div className="image-placeholder">No image selected</div>}<button type="button" className="secondary" onClick={()=>setPicker(true)}>Choose image ↗</button></section>}</aside></div>
  {config.gallery&&<section className="panel gallery-panel"><div className="panel-heading"><div><h2>Project gallery</h2><p className="field-help">Choose a cover, arrange your photographs and add accessible descriptions.</p></div><button type="button" className="secondary" onClick={()=>setPicker(true)}>+ Add photographs</button></div>{record.images.length?<div className="gallery-grid">{record.images.map((image,index)=><div className="gallery-item" key={image.media_id}><img src={mediaUrl(image.url)} alt={image.alt_text||'Project photograph'}/><label className="checkbox-field"><input type="radio" name="cover" checked={image.is_cover} onChange={()=>set('images',record.images.map((im,i)=>({...im,is_cover:i===index})))}/>Cover photograph</label><input aria-label={'Image '+(index+1)+' description'} value={image.alt_text||''} placeholder="Describe this photograph" onChange={e=>set('images',record.images.map((im,i)=>i===index?{...im,alt_text:e.target.value}:im))}/><div className="row-actions"><button type="button" aria-label={'Move image '+(index+1)+' left'} disabled={index===0} onClick={()=>reorder(index,-1)}>←</button><button type="button" aria-label={'Move image '+(index+1)+' right'} disabled={index===record.images.length-1} onClick={()=>reorder(index,1)}>→</button><button type="button" onClick={()=>set('images',record.images.filter((_,i)=>i!==index))}>Remove</button></div></div>)}</div>:<div className="empty-state"><p>Add your first photograph to begin the gallery.</p></div>}</section>}
  <div className="save-bar"><span>{dirty?'Unsaved changes':'All changes saved'}</span><button className="primary" disabled={busy}>{busy?'Saving…':'Save '+config.singular} ↗</button></div></fieldset></form>:<section className="panel"><div className="list-toolbar"><input aria-label="Search content" type="search" placeholder={'Search '+config.title.toLowerCase()+'…'} value={query} onChange={e=>setQuery(e.target.value)}/>{config.statuses&&<select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{config.statuses.map(s=><option key={s}>{s}</option>)}</select>}<span>{visible.length} entries</span></div>{loading?<p className="empty-state" role="status">Loading your content…</p>:visible.length?<div className="table-scroll"><table><thead><tr><th>Name</th><th>Status</th><th>Languages</th><th>Actions</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><button className="title-button" onClick={()=>begin(item)}>{titleOf(item)}</button><small>{item.slug||item.company}{item.is_featured?' · Featured':''}</small></td><td><span className={'badge '+(item.status|| (item.is_active?'published':'archived'))}>{item.status||(item.is_active?'active':'inactive')}</span></td><td><span className="language-indicator">EN / TR</span></td><td><div className="row-actions"><button onClick={()=>begin(item)}>Edit</button><button className="danger-text" disabled={busy} onClick={()=>remove(item)}>{config.statuses?'Delete':'Deactivate'}</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><span className="empty-mark">+</span><h2>{query||filter!=='all'?'Nothing matches your search.':'A fresh page for your studio.'}</h2><p>{query||filter!=='all'?'Try a different search or status.':'Add your first '+config.singular+' to get started.'}</p>{!query&&filter==='all'&&<button className="secondary" onClick={()=>begin(emptyRecord(config))}>Create {config.singular} ↗</button>}{error&&<button onClick={load}>Try again</button>}</div>}</section>}
  {picker&&<MediaPicker onSelect={selected} onClose={()=>setPicker(false)}/>}
 </main>;
}
function localDate(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
