'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api-client';
export default function Messages(){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{setItems(await api('/admin/contact-messages'));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function status(item,value){setBusy(true);setError('');try{const result=await api('/admin/contact-messages/'+item.id+'/'+value,{method:'PATCH'});setItems(list=>list.map(m=>m.id===result.id?result:m));setSelected(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(){if(!window.confirm('Permanently delete this message and its pending notification?'))return;setBusy(true);try{await api('/admin/contact-messages/'+selected.id,{method:'DELETE'});setItems(list=>list.filter(m=>m.id!==selected.id));setSelected(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const visible=items.filter(m=>(filter==='all'||m.status===filter)&&[m.first_name,m.last_name,m.subject,m.email].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <main className="content"><div className="page-heading"><div><p className="eyebrow">CONVERSATIONS START HERE</p><h1>Studio inbox.</h1><p>Make room for the next idea, collaboration or commission.</p></div><span className="badge unread">{items.filter(m=>m.status==='unread').length} unread</span></div>{error&&<p className="notice error" role="alert">{error}<button onClick={load}>Retry</button></p>}<div className="inbox-layout"><section className="panel inbox-list"><div className="list-toolbar"><input type="search" aria-label="Search messages" placeholder="Search conversations…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter messages" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','unread','read','archived'].map(v=><option key={v} value={v}>{v==='all'?'All messages':v}</option>)}</select></div>{loading?<p role="status">Loading messages…</p>:visible.length?visible.map(item=><button className={'message-summary '+(selected?.id===item.id?'selected':'')} key={item.id} onClick={()=>setSelected(item)}><span><strong>{item.first_name} {item.last_name}</strong><span className={'badge '+item.status}>{item.status}</span></span><b>{item.subject}</b><p>{item.message}</p></button>):<div className="empty-state"><h2>All quiet for now.</h2><p>New website enquiries will appear here.</p></div>}</section><section className="panel message-detail">{selected?<><span className={'badge '+selected.status}>{selected.status}</span><h2>{selected.subject}</h2><dl><dt>From</dt><dd>{selected.first_name} {selected.last_name}</dd><dt>Email</dt><dd><a href={'mailto:'+selected.email}>{selected.email}</a></dd>{selected.phone&&<><dt>Phone</dt><dd><a href={'tel:'+selected.phone}>{selected.phone}</a></dd></>}</dl><p className="message-body">{selected.message}</p><div className="message-actions"><button disabled={busy} className="secondary" onClick={()=>status(selected,selected.status==='unread'?'read':'unread')}>{selected.status==='unread'?'Mark as read':'Mark as unread'}</button><button disabled={busy||selected.status==='archived'} className="secondary" onClick={()=>status(selected,'archive')}>Archive</button><button className="danger-text" disabled={busy} onClick={remove}>Delete message</button></div></>:<div className="empty-state"><span className="empty-mark">↗</span><h2>A conversation awaits.</h2><p>Select a message to read its details.</p></div>}</section></div></main>;
}
