import Link from 'next/link';
import { sitePath } from '../lib/site-path';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { copy, paths } from '../lib/content';
import { Brand } from './site-header';

export function Eyebrow({ children, light = false }) { return <p className={`eyebrow ${light ? 'eyebrow-light' : ''}`}><span/>{children}</p>; }
export function TextLink({ href, children, className = '' }) { return <Link className={`text-link ${className}`} href={href}>{children}<ArrowUpRight size={18}/></Link>; }
export function Picture({ src, alt, className = '', eager = false }) { return <img src={src} alt={alt} className={`picture ${className}`} width="1600" height="1100" loading={eager ? 'eager' : 'lazy'} fetchPriority={eager ? 'high' : 'auto'} decoding="async"/>; }
export function PageIntro({ eyebrow, title, intro }) { return <section className="shell page-intro"><Eyebrow>{eyebrow}</Eyebrow><div className="page-intro-grid"><h1>{title}</h1><p>{intro}</p></div></section>; }
export function SectionHeading({ label, title, description, href, link }) { return <div className="section-heading"><div><Eyebrow>{label}</Eyebrow><h2>{title}</h2>{description && <p className="section-description">{description}</p>}</div>{href && <TextLink href={href}>{link}</TextLink>}</div>; }
export function ProjectCard({ project, locale }) { const p = project[locale]; return <Link className="project-card group" href={`/${locale}/projects/${project.slug}`}><div className="project-photo"><Picture src={project.image} alt={`${p.title} — ${p.tag}`}/><span className="project-view"><ArrowUpRight size={24}/></span><span className="project-year">{project.year}</span></div><div className="project-caption"><div><h3>{p.title}</h3><p>{p.tag}</p></div><span>{p.place}</span></div></Link>; }
export function ArticleCard({ article, locale }) { const a = article[locale]; return <article className="article-card"><Link className="article-image" href={`/${locale}/insights/${article.slug}`}><Picture src={article.image} alt={a.title}/><span><ArrowUpRight/></span></Link><div className="article-meta"><span>{a.category}</span><time dateTime={article.date}>{new Date(`${article.date}T12:00:00Z`).toLocaleDateString(locale === 'tr' ? 'tr-TR' : 'en-GB', { day:'numeric',month:'short',year:'numeric',timeZone:'UTC' })}</time></div><h3><Link href={`/${locale}/insights/${article.slug}`}>{a.title}</Link></h3><p>{a.excerpt}</p><TextLink href={`/${locale}/insights/${article.slug}`}>{copy[locale].insights.read}</TextLink></article>; }
export function Stats({ locale }) { return <div className="stats shell">{copy[locale].stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>; }
export function CallToAction({ locale }) { const c = copy[locale]; return <section className="cta"><div className="shell cta-inner"><div><Eyebrow light>{c.cta.label}</Eyebrow><h2>{c.cta.title}</h2><p>{c.cta.text}</p></div><Link className="cta-link" href={`/${locale}/contact`}><span>{c.start}</span><ArrowUpRight size={42} strokeWidth={1}/></Link></div><span className="cta-decoration" aria-hidden="true">f.</span></section>; }
export function SiteFooter({ locale }) { const c = copy[locale]; return <footer className="site-footer shell"><div className="footer-grid"><div><Link href={`/${locale}`} aria-label="Forma Studio"><Brand/></Link><p className="footer-description">{c.footer.description}</p></div><div><h3>{c.footer.explore}</h3><nav aria-label={locale === 'en' ? 'Footer navigation' : 'Alt menü'}>{paths.slice(1).map((path,i) => <Link key={path} href={`/${locale}${path}`}>{c.nav[i+1]}</Link>)}</nav></div><div><h3>{c.footer.find}</h3><p>{c.footer.location}</p><p className="footer-time">41°01′ N &nbsp; 28°58′ E</p><TextLink href={`/${locale}/contact`}>{c.start}</TextLink></div><div className="footer-note"><ArrowRight size={28} strokeWidth={1}/><p>{locale === 'en' ? 'A fresh perspective is always a good place to start.' : 'Taze bir bakış, başlamak için her zaman iyi bir yerdir.'}</p></div></div><div className="footer-bottom"><span>{c.footer.note}</span><Link href={`/${locale}/privacy`}>{c.footer.privacy}</Link><div><a href={sitePath("/en/")} hrefLang="en" lang="en">English</a><span>/</span><a href={sitePath("/tr/")} hrefLang="tr" lang="tr">Türkçe</a></div></div></footer>; }
