"""create project and contact tables"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("admin_users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("role", sa.String(30), nullable=False, server_default="admin"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("admin_sessions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("admin_users.id", ondelete="CASCADE"), nullable=False), sa.Column("refresh_token_hash", sa.String(128), nullable=False, unique=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("last_used_at", sa.DateTime(timezone=True)))
    op.create_table("project_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("slug", sa.String(80), nullable=False, unique=True), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("project_category_translations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("project_categories.id", ondelete="CASCADE"), nullable=False), sa.Column("language_code", sa.String(2), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.UniqueConstraint("category_id", "language_code"))
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("slug", sa.String(140), nullable=False, unique=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("project_categories.id"), nullable=False), sa.Column("location", sa.String(180), nullable=False), sa.Column("area_sqm", sa.Integer()), sa.Column("construction_year", sa.Integer()), sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("status", sa.String(20), nullable=False, server_default="draft"), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("project_translations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("language_code", sa.String(2), nullable=False), sa.Column("title", sa.String(180), nullable=False), sa.Column("concept", sa.String(240), nullable=False), sa.Column("short_description", sa.String(500), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("challenge", sa.Text()), sa.Column("approach", sa.Text()), sa.Column("outcome", sa.Text()), sa.UniqueConstraint("project_id", "language_code"))
    op.create_table("media_files", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("storage_key", sa.String(500), nullable=False, unique=True), sa.Column("public_url", sa.String(1000), nullable=False), sa.Column("file_name", sa.String(255), nullable=False), sa.Column("mime_type", sa.String(80), nullable=False), sa.Column("file_size", sa.Integer(), nullable=False), sa.Column("alt_text", sa.String(255)), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("project_images", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("media_id", sa.Integer(), sa.ForeignKey("media_files.id"), nullable=False), sa.Column("alt_text", sa.String(255)), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_cover", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_table("contact_messages", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("first_name", sa.String(100), nullable=False), sa.Column("last_name", sa.String(100), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("phone", sa.String(40)), sa.Column("subject", sa.String(200), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="unread"), sa.Column("read_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("notification_jobs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("type", sa.String(80), nullable=False), sa.Column("payload_json", sa.JSON(), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("available_at", sa.DateTime(timezone=True)), sa.Column("processed_at", sa.DateTime(timezone=True)), sa.Column("last_error", sa.Text()), sa.Column("contact_message_id", sa.Integer(), sa.ForeignKey("contact_messages.id", ondelete="CASCADE")))
    op.create_table("testimonials", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("client_name", sa.String(160), nullable=False), sa.Column("company", sa.String(160)), sa.Column("role", sa.String(160)), sa.Column("rating", sa.Integer(), nullable=False), sa.Column("avatar_media_id", sa.Integer(), sa.ForeignKey("media_files.id")), sa.Column("status", sa.String(20), nullable=False, server_default="draft"), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("testimonial_translations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("testimonial_id", sa.Integer(), sa.ForeignKey("testimonials.id", ondelete="CASCADE"), nullable=False), sa.Column("language_code", sa.String(2), nullable=False), sa.Column("quote", sa.Text(), nullable=False), sa.UniqueConstraint("testimonial_id", "language_code"))
    op.create_table("blog_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("slug", sa.String(80), nullable=False, unique=True), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("blog_category_translations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("blog_categories.id", ondelete="CASCADE"), nullable=False), sa.Column("language_code", sa.String(2), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.UniqueConstraint("category_id", "language_code"))
    op.create_table("articles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("slug", sa.String(160), nullable=False, unique=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("blog_categories.id")), sa.Column("author_id", sa.Integer(), sa.ForeignKey("admin_users.id")), sa.Column("cover_media_id", sa.Integer(), sa.ForeignKey("media_files.id")), sa.Column("status", sa.String(20), nullable=False, server_default="draft"), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("article_translations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("article_id", sa.Integer(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False), sa.Column("language_code", sa.String(2), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("excerpt", sa.String(600), nullable=False), sa.Column("content_html", sa.Text(), nullable=False), sa.UniqueConstraint("article_id", "language_code"))

def downgrade():
    for table in ["article_translations", "articles", "blog_category_translations", "blog_categories", "testimonial_translations", "testimonials", "notification_jobs", "contact_messages", "project_images", "media_files", "project_translations", "projects", "project_category_translations", "project_categories", "admin_sessions", "admin_users"]:
        op.drop_table(table)
